//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int id { get; set; }
        public Nullable<int> idhoadon { get; set; }
        public Nullable<int> idproduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> tiendathanhtoan { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> realprice { get; set; }
        public string state { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
