//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> saleprice { get; set; }
        public Nullable<long> importprice { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
