//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACK
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int id { get; set; }
        public string idpromotions { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> datefrom { get; set; }
        public Nullable<System.DateTime> dateto { get; set; }
        public string idproduct { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> deleted { get; set; }
    }
}
